### PR TITLE
Add AILIN Token

### PR DESCRIPTION
**Pull request by ailinio**

### CODE REVIEW

**Comment by ailinio** [comment]
:)
transaction link: https://cardanoscan.io/transaction/c060819403a0870bc8469c06a51718da6929857452990b1a9c75367e347b491f

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!
Do you have a description of your token and tokenomics on your website?
Do you have a social media channel like Twitter?

**Comment by ailinio** [comment]
Hello, after a long discussion yesterday we decided to stop the project. It would be nice if you could send us back the 50 Ada (45 after transaction costs). Many thanks for your effort and good luck. Greetings

Adress: addr1qyk3gnj9vxur2xlznlqzgrn03d62lvujka895ugx7dkqy86e3px0ju7ere3435uulparsmftsgqh50kgpyqs0lu4xwmsyglt5x

**Comment by MuesliSwapTeam** [comment]
No problem; we have refunded you the verification fee.

**Pull request closed without merging**
