### PR TITLE
Add EZY token verification

### PR DESCRIPTION
**Pull request by sinweitan**
b57794691515d0bb5935371855b8efebd65152ca12148f8e8c50a7755c9b5bca

### CODE REVIEW

**Comment by sinweitan** [comment]
You can find us on twitter at https://twitter.com/eggscapeclub
or discord at https://discord.gg/MXhPZyXAJZ

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
We might have missed it, but could you point us to the tokenomics/distribution of the token?
The tokenomics on your website seem to be for another token.

**Comment by sinweitan** [comment]
Good afternoon from where I am from! Glad to hear from you. Here is the link to our tokenomics.
https://eggscape.io/tokenomics

**Comment by MuesliSwapTeam** [comment]
Great, thank you!

**Pull request merged**
