### PR TITLE
BVT Token Verification

### PR DESCRIPTION
**Pull request by bullvertigo**

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the pull request!
We might have missed it, but do you have your tokenomics published on your website?

**Comment by bullvertigo** [comment]
hi,
our tokenomics is on our docs website:
https://bullvertigo.gitbook.io

https://bullvertigo.gitbook.io/bullvertigo/bullvertigo-token/tokenomics

i hope is ok or we could add it on a website page too..

let me know.

thanks
mark



Il giorno domenica 16 ottobre 2022, MuesliSwap Team <
***@***.***> ha scritto:
> Hi, thank you for the pull request!
> We might have missed it, but do you have your tokenomics published on
your website?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/PHFwGkXXnpyl02Be-z4rXogfEF7FQofTB4_2_NcK54qFCbj6fMcGMr2HqOyUGVzHShFo3oBZfKfJcC8a54ydXl11SUi1pYBfXgVjtIXhZUxIJLjJPixb6YkF28XToFwkaRs1XRyZGhpyik8PSqyWDI4CBt3Slu3hcqPn_Z75jYGSBopj_fdlO6USCWFgj-LwXGyKO5szABERYO4YZexycXs-_8PWbhPUQ23UGIutK4D-zGLfpA=s0-d-e1-ft#https://github.com/notifications/beacon/AZ4UZCOLHROPSCRHCKWCBVTWDPWSZA5CNFSM6AAAAAARCP7YLOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSMJKNKI.gif>Message
ID: <MuesliSwapTeam/muesliswap-token-verification/pull/149/
***@***.***>

**Comment by bullvertigo** [comment]
oh..and is linked from the main site and member area too..

Il giorno giovedì 20 ottobre 2022, Mark Dosier ***@***.***> ha
scritto:
> hi,
> our tokenomics is on our docs website:
> https://bullvertigo.gitbook.io
>
> https://bullvertigo.gitbook.io/bullvertigo/bullvertigo-token/tokenomics
>
> i hope is ok or we could add it on a website page too..
>
> let me know.
>
> thanks
> mark
>
>
>
> Il giorno domenica 16 ottobre 2022, MuesliSwap Team <
***@***.***> ha scritto:
>> Hi, thank you for the pull request!
>> We might have missed it, but do you have your tokenomics published on
your website?
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/PHFwGkXXnpyl02Be-z4rXogfEF7FQofTB4_2_NcK54qFCbj6fMcGMr2HqOyUGVzHShFo3oBZfKfJcC8a54ydXl11SUi1pYBfXgVjtIXhZUxIJLjJPixb6YkF28XToFwkaRs1XRyZGhpyik8PSqyWDI4CBt3Slu3hcqPn_Z75jYGSBopj_fdlO6USCWFgj-LwXGyKO5szABERYO4YZexycXs-_8PWbhPUQ23UGIutK4D-zGLfpA=s0-d-e1-ft#https://github.com/notifications/beacon/AZ4UZCOLHROPSCRHCKWCBVTWDPWSZA5CNFSM6AAAAAARCP7YLOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSMJKNKI.gif>Message
ID: <MuesliSwapTeam/muesliswap-token-verification/pull/149/
***@***.***>

**Comment by bullvertigo** [comment]
you must be very busy with your development.
still waiting since 2 weeks..

Il giorno giovedì 20 ottobre 2022, Mark Dosier ***@***.***> ha
scritto:
> oh..and is linked from the main site and member area too..
>
> Il giorno giovedì 20 ottobre 2022, Mark Dosier ***@***.***> ha
scritto:
>> hi,
>> our tokenomics is on our docs website:
>> https://bullvertigo.gitbook.io
>>
>> https://bullvertigo.gitbook.io/bullvertigo/bullvertigo-token/tokenomics
>>
>> i hope is ok or we could add it on a website page too..
>>
>> let me know.
>>
>> thanks
>> mark
>>
>>
>>
>> Il giorno domenica 16 ottobre 2022, MuesliSwap Team <
***@***.***> ha scritto:
>>> Hi, thank you for the pull request!
>>> We might have missed it, but do you have your tokenomics published on
your website?
>>>
>>> —
>>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/PHFwGkXXnpyl02Be-z4rXogfEF7FQofTB4_2_NcK54qFCbj6fMcGMr2HqOyUGVzHShFo3oBZfKfJcC8a54ydXl11SUi1pYBfXgVjtIXhZUxIJLjJPixb6YkF28XToFwkaRs1XRyZGhpyik8PSqyWDI4CBt3Slu3hcqPn_Z75jYGSBopj_fdlO6USCWFgj-LwXGyKO5szABERYO4YZexycXs-_8PWbhPUQ23UGIutK4D-zGLfpA=s0-d-e1-ft#https://github.com/notifications/beacon/AZ4UZCOLHROPSCRHCKWCBVTWDPWSZA5CNFSM6AAAAAARCP7YLOWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSMJKNKI.gif>Message
ID: <MuesliSwapTeam/muesliswap-token-verification/pull/149/
***@***.***>

**Comment by MuesliSwapTeam** [comment]
Thank you for the update!
You have been verified!

**Comment by bullvertigo** [comment]
Thanks a lot!
On muesliswap BVT is  still unverified, is there anything else that i
should do
in order  to be veried please?



Il giorno mer 26 ott 2022 alle ore 23:42 MuesliSwap Team <
***@***.***> ha scritto:

**Pull request merged**
