### PR TITLE
QuantumAI Token - QAI Submission

### PR DESCRIPTION
**Pull request by C-QuantumAi**
## Description
Registration listing request for QuantumAI Token - QAI on Muesliswap.

## Type of change
-[x] Listing to Muesliswap DEX Platform.

### CODE REVIEW

**Comment by C-QuantumAi** [comment]
50 ADA has been sent to the address listed (addr1q80tpha9tdm7rkw4enp3drad0l05wx5tjvn0qf4pa4peprzf23273axsqshqwlp9he0nq9tjf8yuf4tu4eej64277yzskzqlf2) 
to cover the verification fee.

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the request and sorry for the delay.
We have a few questions about the validity of the whitepaper presented on your website.
Is the list of authors on the second page correct and are they all affiliated with the project?

**Comment by C-QuantumAi** [comment]
The authors in the whitepaper are used as a reference for the whitepaper. The authors mentioned are the original creators of the technology that we will be using to implement into our future smart contract. We will be using open-source coding that is setup by the authors, but they are not directly affiliated to the project it self. They are strictly mentioned in the whitepaper to give credit to the creators of the original technology that we will build on top of.

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the clarification!
At the moment, it looks like the authors themselves are also part of the project. 
Therefore, we would ask you to replace the paper with a short document where you cite the authors. The document does not have to be lengthy but should contain:

1. Your token description.
2. Tokenomics (which you already provided).
3. A short explanation of how you plan to build on top of that paper.

Of course, if you don't want to do that, you can drop your wallet address, and we will return the 50 ADA.

**Comment by C-QuantumAi** [comment]
Not a problem, my team will start working on that immediately and will return with a short version as to how we plan on building on top of that whitepaper. Thank you for getting back to me.

**Comment by C-QuantumAi** [comment]
Hello,
The shortened version of the whitepaper has been created with brief explanation of our project's goals, vision and future development and how we plan on implementing the previous whitepaper into our project along with references, citations and hyperlinks. Hope to hear back from you soon!

Link below is the updated whitepaper 
https://github.com/C-QuantumAi/QuantumAI/blob/main/QuantumAI%20Whitepaper%20updated.pdf

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the effort, we really appreciate it!
However, the passages which are taken from the paper should also be marked as such. There are many useful guides for scientific citation available online such as [this one](https://guides.libraries.psu.edu/apaquickguide/intext#:~:text=For%20every%20in%2Dtext%20citation,14).

**Comment by C-QuantumAi** [comment]
We will add the citations to the pages, but it would be nice if your team would've added this information to your GitHub listing requirements list so we wouldn't have to play this back and forward game to avoid possible set backs of anyone's project.

**Comment by C-QuantumAi** [comment]
https://github.com/C-QuantumAi/QuantumAI/blob/main/QuantumAI%20Whitepaper%20updated.pdf
The citations have been added to the pages requested.

**Pull request merged**
