### PR TITLE
AGC token verification files

### PR DESCRIPTION
**Pull request by woofpool**
Once the 50 ADA has been transferred to payment address, a comment with Tx ID will be added to PR

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hey, thanks a lot for the pull request!
Do you have a public website with a token description, policy-id, and tokenomics?

**Comment by AGCcore** [comment]
Hi, we don't have a dedicated website as yet.

https://twitter.com/AGC_Token
https://www.facebook.com/profile.php?id=100082715241483
https://discord.com/channels/908150771214860360/995780804556898365

We do Have a whitepaper that's still being edited. but from the links I provided you can see that we have a community in place, our token is used to enter our Esports tournaments. So we set up an orderbook with you guys to make this easier. 
We are not a DAO nothing fancy with our tokenomics we minted 300mil mint/burn contract is closed, the tokens are available for players or investors. 

We will have a website soon, we have submitted a proposal for funding in catalyst fund 10, once we are successful a web application will be build where we will migrate all operations.
So we hope that we can get the token verified so that it's easier to identify and find on your dex.

**Comment by MuesliSwapTeam** [comment]
Hi, thanks a lot for the quick reply!
The website is not strictly necessary, but we require some publicly available page with a short token description, tokenomics, and, most importantly, the policy-id. This is just for investor to be able to access that information easily.
Alternatively, you could also make a post on Twitter including that information, add it to your Twitter bio, set up a Google Doc or Wiki Page, or we wait until the whitepaper or website is released.

**Comment by AGCcore** [comment]
Hi let me know if this will work:
https://twitter.com/AGC_Token
link in bio
https://docs.google.com/document/d/1uObDWxmaZflTNSWOc6gkJ4ZNsNZBeJxQzyuXFU8OQJ4/edit

**Comment by MuesliSwapTeam** [comment]
Thanks a lot, that looks great!
You have just been verified!

**Pull request merged**
