### PR TITLE
Goldie Dog Verification Request 

### PR DESCRIPTION
**Pull request by ssbright**
Payment transaction ID:

c1d543e32c4643bd59b2ac85fadcd204d37cf658eaae7576e1326fb5068d0bc7

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hey, thanks for the pull request, but the website does not seem to be working yet.

**Comment by ssbright** [comment]
Sorry about that! It should be live shorty. Should we resubmit the pull request when that happens or email you and let you know?

**Comment by ssbright** [comment]
The website is live now! Can we merge now?

**Comment by MuesliSwapTeam** [comment]
Thanks for the update! You have been verified!

**Pull request merged**
