### PR TITLE
961f2cac0bb1967d74691af179350c1e1062c7298d1f7be1e4696e31.$DERP

### PR DESCRIPTION
**Pull request by anthgenova**
$DERP verification

### CODE REVIEW

**Comment by anthgenova** [comment]
Txn:   ee843d6a83aeac1cc8bf87362767f731b76c3305798bd80d644ef5fdf5b3731f

**Comment by MuesliSwapTeam** [comment]
Thanks for the pull request!
Sorry in case we missed it, but did you publish an overview of your Tokenomics somewhere?
Besides that, everything looks good, and we will be happy to have you verified!

**Comment by anthgenova** [comment]
It is in the lite-paper, https://derp.link/$derp-lite-paper.pdf , which can
be found in the Discord, https://discord.gg/6xyaWCWb .

Tokenomics can be found in section 8, pages 22-24.

Please let me know if you have any more questions!

**Comment by MuesliSwapTeam** [comment]
Thanks a lot! You are now verified.

**Comment by anthgenova** [comment]
Thank you so much!!

**Comment by anthgenova** [comment]
Does verifying add $DERP to the featured page?

**Pull request merged**
