### PR TITLE
Add cardanogold

### PR DESCRIPTION
**Pull request by similiken**
Mazzanti tokens
Payment transaction id: 14f97c9aa5040f2e1b2b69c2ad383ea68e78d162f5adf7e9b617216a35ae67ac
https://mazzantitokens.wordpress.com/
https://twitter.com/GabrielMazzant3
https://discord.com/invite/AJUed2mtWr

discord contact: similiken#0250

### CODE REVIEW

**Comment by similiken** [comment]
transaction ID for cardanosilver verification: 400a661f3e9b9900c37d73a3f57df0ce8cf42b062c9bb61ce03c079e95d5bdb3

**Comment by similiken** [comment]
transaction id for cardanocopper verification: 85b39badb32d496b82d14d71b11a32babf09dc565fe911d54c9f9139008f5c2d

**Comment by similiken** [comment]
transaction id for peace verification: 18a1c7f97957600286f26bb0d6bc56e0746821124ff00848848b8dbc76bc4de0

**Comment by similiken** [comment]
transaction id for love verification: c1b7d634e46b229ae303d602c38ed297a73bad4c902985133d4289a5ad3475ae

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!
Do you have individual charts listing the tokenomics of your tokens?
In case I missed them, please just send a link to the page.

**Comment by similiken** [comment]
This site has all of the tokenomics. https://mazzantitokens.wordpress.com/
[https://mazzantitokens.files.wordpress.com/2022/12/mshare-1.jpg]<https://mazzantitokens.wordpress.com/>
Mazzanti Tokens - Cardano speculative assets<https://mazzantitokens.wordpress.com/>
Mazzanti Tokens - Cardano speculative assets
mazzantitokens.wordpress.com

________________________________

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the update!
Your tokens have just been verified!

**Pull request merged**
