### PR TITLE
ADAPE Token

### PR DESCRIPTION
**Pull request by adapetoken**
50 ADA Transaction ID 91672abf5109ece228bddb5bf894a0fcfaebf43e4903218d7729662d4150b32e

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the request!
In our requirements, we ask projects to provide a website with information on the policy id, tokenomics, and a token description. 
Do you have such a website or can provide the information on Twitter?
Best regards!

**Comment by adapetoken** [comment]
I sent you the information from the twitter dm page.

https://cardanoscan.io/token/a561173b1e3f145933f94351f79e16b6f90dc8d549ac6f26867233c04144415045

https://exchange.sundaeswap.finance/#/swap?swap_from=a561173b1e3f145933f94351f79e16b6f90dc8d549ac6f26867233c0.4144415045&swap_to=cardano.ada

https://www.cardanocube.io/projects/adape-token

https://www.jpg.store/collection/adapetoken


MuesliSwap Team ***@***.***>, 13 Mar 2022 Paz, 04:28
tarihinde şunu yazdı:

**Comment by MuesliSwapTeam** [comment]
Thank you for the effort of sending those links!
However, the pages do not reveal information about tokenomics or a more detailed token description.
Could you also provide this information on your Twitter page?

**Comment by adapetoken** [comment]
https://twitter.com/adapetoken/status/1502946133127188488?s=20&t=a_Hv8RTrCJSEys9lV3Zbtg

**Comment by adapetoken** [comment]
https://drive.google.com/file/d/14pcxxg68L5U_UuJz8d9AjjbSJzroDFrA/view?usp=sharing

**Comment by adapetoken** [comment]
https://twitter.com/adapetoken/status/1502946133127188488?s=20&t=jRZs6-ZnZ7SDJ4lyplYMpw


MuesliSwap Team ***@***.***>, 13 Mar 2022 Paz, 12:34
tarihinde şunu yazdı:

**Pull request merged**
