### PR TITLE
Create BubbleToken

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
50 ADA comming to town

### CODE REVIEW

**Comment by GabrielMazzanti** [comment]
Hello

Here is the payment

https://cardanoscan.io/transaction/6af7bc195053176da4b265c2ff54ef44c21a6e5837466da258995714f899e83f

**Comment by GabrielMazzanti** [comment]
Also do I need to count in Decimals when i chose amounts ?

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!
Do you also have an overview of the distribution (tokenomics) for Bubble on your website?
Besides that, everything looks good!

**Comment by GabrielMazzanti** [comment]
Hello the tokenomics are on cnftbubbletoken on twitter in the images

Le lun. 6 mars 2023 à 00:05, MuesliSwap Team ***@***.***> a
écrit :

**Comment by GabrielMazzanti** [comment]
Here it is https://twitter.com/CNFTBubbleToken

Since this is a dao and Reward Token, the tokenomics might really change
according to on wich direction owners wan't it to go

Le lun. 6 mars 2023 à 00:05, MuesliSwap Team ***@***.***> a
écrit :

**Comment by MuesliSwapTeam** [comment]
Thanks for the update!
You have just been verified!

**Pull request merged**
