### PR TITLE
SKULL

### PR DESCRIPTION
**Pull request by kriscarilloxyz**
https://cardanoscan.io/transaction/e082d584d7d79ab1d55f46fe9ad14603bbd37db708cda7a0aedabb7b9d5d4aff

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for submitting a pull request and sending the verification fee!
We have decided to update our minimum requirements to include: 

🌐 A website
📝 A token description 
📊 Tokenomics
✉️ Contact information (e.g., twitter, email)

The website in your pull request contains your contact information, which is really good!
However, we would also like to see a page with a token description and tokenomics.  
If we just missed that information, feel free to point us to the correct page, and if you have any questions feel free to contact us. Of course, if you do not wish to implement these changes we can send you back the verification fee.

Best regards, 
Your MuesliSwap Team

**Comment by kriscarilloxyz** [comment]
https://nemo.global

Should be there. Thank you.

**Comment by kriscarilloxyz** [comment]
Just a quick question does muesli support GIF formats on images?

**Comment by MuesliSwapTeam** [comment]
Great, you are now verified!  
Yes, we also support GIFs.

**Pull request merged**
