### PR TITLE
Added PocketChange

### PR DESCRIPTION
**Pull request by kardall**
Disappeared, re-adding.

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
Could you also add the token image?

**Comment by MuesliSwapTeam** [comment]
Thank you, looks good!  
Could you send the transaction hash?

**Comment by kardall** [comment]
What transaction hash are you referring to?

**Comment by MuesliSwapTeam** [comment]
The verification fee.

**Comment by kardall** [comment]
Ok here is the tx hash: 96b3bbf9badd40e38cb1abd85f469f4137ca89050947826980a4775de4b85731

**Pull request merged**
