### PR TITLE
Token verification for Cardano Clanns CNFT Project

### PR DESCRIPTION
**Pull request by LacbDev**
Token verification for Cardano Clanns CNFT Project

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Thank you very much for the pull request!
There is a description of the NFTs on your website, but do you also have a description of the token, including the tokenomics?
Besides that, could you submit the verification fee of 50 ADA?

**Comment by LacbDev** [comment]
Hey @everyone ☘️

This is a channel for information regarding the introduction and use of the Cardano Clanns token $PUNT. 

What is $PUNT?
The Cardano Clanns token, $PUNT, is the official token for the Cardano Clanns. The name comes from the old currency used in Ireland and was developed by the Clann team in April 2022. This is a token of limited supply set at 500 million tokens. The full breakdown can be found in the Clann Stone Paper which will be released soon. The coin will be greatly utilized as part of the project moving forward and will fuel the Clann ecosystem and be the native currency in the Cardano Clanns Clubhouse once integrated in the Metaverse.

How to get $PUNT?
You will be able to get $PUNT the following ways:
☘️Monthly airdrops for holding your Clanns 
(plans for future staking platform)
☘️Community rewards 
☘️Prizes for gaming events and poker tournaments
☘️Swapping ADA on decentralised exchange

Uses for $PUNT
☘️Entry to gaming nights & poker events 
☘️Redeem for discount at future mints

**Comment by LacbDev** [comment]
Please let me know where to send verification ADA to.  Many thanks.

**Comment by LacbDev** [comment]
Screenshot_2023-03-14-19-16-43-16_e2d5b3f32b79de1d45acd1fad96fbb0f

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the update! You can submit the payment to the following address:
[addr1q80tpha9tdm7rkw4enp3drad0l05wx5tjvn0qf4pa4peprzf23273axsqshqwlp9he0nq9tjf8yuf4tu4eej64277yzskzqlf2](https://cardanoscan.io/address/01deb0dfa55b77e1d9d5ccc3168fad7fdf471a8b9326f026a1ed43908c495455e8f4d0042e077c25be5f30157249c9c4d57cae732d555ef105)

**Pull request merged**
