### PR TITLE
Not Even Token Verification

### PR DESCRIPTION
**Pull request by oz15**
re-submitting pull request for the verification of Not Even Token.

### CODE REVIEW

**Comment by oz15** [comment]
fee transaction ID: 931bb64c3baf103e3fa858d450fd276c332f7c4d125b1210dc8c11fd33bbedf9

**Comment by oz15** [comment]
i am happy to accept the fee, but the organization is philanthropic by nature and not for profit

**Comment by MuesliSwapTeam** [comment]
Hi, thanks a lot for the pull request and for submitting the verification fee!
There is a page on Tokenomics on your website, but could you add the token distribution (e.g., Pre-sale, Airdrop, Staking, Team, etc.) to it? 
Also, do you have a social media platform?

**Comment by oz15** [comment]
Currently all these coins are in reserve and the methods of distribution haven't been decided on by the club yet but it will be a main priority to update this page as coins are deployed.
It is a private club so we have no social media right now, until such time the club decides it would benefit our purpose.

**Comment by oz15** [comment]
The coins in their entirety have been distributed to the club. I updated the website to display that all the coins are in circulation and have been allocated to the club reserve.

**Comment by MuesliSwapTeam** [comment]
Thank you for the update, but how are you going to distribute them? The point of the tokenomics is for users to have an overview of how many tokens will be sold, how many are held by the team, etc.

**Comment by oz15** [comment]
They have all been distributed to the club. No sales no other distribution. Why are the requirements to be so much more detailed than the page on MILKs tokenomics? It doesn't state how many you sold or how much went to the team... Etc

**Comment by oz15** [comment]
We are trying to comply with laws and regulations while conducting experiments on systems of value using blockchain, we are having a hard time navigating applicable policies and would be happy to accept further direction on how to legitimize our token on your platform. If the project cannot be verified as is then perhaps we can work out whether or not it has any potential to become verified or if we should seek other options.

**Pull request merged**
