### PR TITLE
Hatercoin Verification Request

### PR DESCRIPTION
**Pull request by enri0602**
Hi there, 

I'd like to verify Hatercoin, my new community token.

### CODE REVIEW

**Comment by enri0602** [comment]
Transaction ID: 8ca48fb1473ee12c87333dd47f43019681640a04f42f2c4df59665f5078257f8

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!
Could you please add the policy-id somewhere on your website?
Besides that, everything looks good!

**Comment by enri0602** [comment]
Thanks for checking my request! I added the Policy ID at the bottom of my website.

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the update, you have just been verified!

**Pull request merged**
