### PR TITLE
Fluff token

### PR DESCRIPTION
**Pull request by tqueri**

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hey, thanks a lot, and congrats on your project!
Sry if we missed it, but could you please publish the policy ID and tokenomics of $fluff on your website? 
Besides that, your website looks great, and we'll be happy to have you verified!

**Comment by TedNationCNFT** [comment]
> Hey, thanks a lot, and congrats on your project! Sry if we missed it, but could you please publish the policy ID and tokenomics of $fluff on your website? Besides that, your website looks great, and we'll be happy to have you verified!

Hey guys, just wanted to give you guys know, that I'm currently on vacation in Africa, therefore not that responsive as usual. I try to add the policy ID aswell as tokenomics to our website in the next days and let you guys know in here when done :)

Is it okay to just make a button / link from our website to our github where all that is written down? Would be easier for me to do during vacation :D

**Comment by MuesliSwapTeam** [comment]
Yes, that would be fine!
Hope you have a great vacation!

**Comment by TedNationCNFT** [comment]
> Yes, that would be fine! Hope you have a great vacation!

Thank you! Very much enjoyed the time and unfortunately our Gitbook took longer than expected... Just released it yesterday, you can find it in our header (Docs) on our website: https://tednation.com/

Hope this meets your expectations :)

Really looking forward on verification 💯

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the update! You are now verified.

**Comment by TedNationCNFT** [comment]
> Thanks a lot for the update! You are now verified.

Hey guys, thanks a lot! Why does it still show "unverified" on muesliswap then? :/
grafik

Best

Michael

**Pull request merged**
