### PR TITLE
APOC token registration

### PR DESCRIPTION
**Pull request by mathieu2em**
Website - ada-apocalypse.com
Twitter - https://twitter.com/ada_apocalypse
Description - Native Horde currency for the ADA Apocalypse ecosystem
Contact info - ada.apocalypse21@gmail.com

Tokenomics 

There will be a total supply of 10,000,000,000 $APOC tokens
Vesting periods implemented over 4 years
STAKING-30%
TEAM -10%
COMMUNITY REWARDS-20%
COMMUNITY DEVELOPMENT-25%
BUYERBONUSES-15%

I have also send over the 50ada they require here is the tx id...
a72707d743c61b1723c2807c5dfa30ed92848dce7eaad0ec2759174cc092c5b0

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the pull request!
Could you also include the policy id and tokenomics on your website, or point us to it?

**Comment by mathieu2em** [comment]
a72707d743c61b1723c2807c5dfa30ed92848dce7eaad0ec2759174cc092c5b0
here is the transactionID for the 50 ADA 

@MuesliSwapTeam 

please let me know if anything else is missing for you to register the token

**Comment by mathieu2em** [comment]
Tokenomics 

There will be a total supply of 10,000,000,000 $APOC tokens
Vesting periods implemented over 4 years
STAKING-30%
TEAM -10%
COMMUNITY REWARDS-20%
COMMUNITY DEVELOPMENT-25%
BUYERBONUSES-15%

**Comment by mathieu2em** [comment]
Website - ada-apocalypse.com
Twitter - https://twitter.com/ada_apocalypse
Description - Native Horde currency for the ADA Apocalypse ecosystem
Contact info - ada.apocalypse21@gmail.com

**Comment by mathieu2em** [comment]
@MuesliSwapTeam

**Comment by MuesliSwapTeam** [comment]
Thanks so much for the update!
Could you please include your policy-id on your website and in your white paper?
Besides that, everything looks great!

**Comment by mathieu2em** [comment]
hi @MuesliSwapTeam , 
Website has now been updated and contains $APOC policy ID (Under 'What utility comes with holding an Apocalypse NFT?' https://apocalypse-nft.io/faqs/)
The horde paper has also been updated, $APOC policy ID can be found on page 13 (Copy can be found on https://apocalypse-nft.io/horde-paper/)

**Comment by MuesliSwapTeam** [comment]
Thank you very much for the update!
You will soon be verified!

**Pull request merged**
