### PR TITLE
Mystery Token

### PR DESCRIPTION
**Pull request by mr-eeee**
Verification files with 50 ADA fee, transaction:

7a945d54717b5a5600891cb6d2f6c9e8dc84f75a61c24a692343fdf1a2777e97

### CODE REVIEW

**Comment by mr-eeee** [comment]
7a945d54717b5a5600891cb6d2f6c9e8dc84f75a61c24a692343fdf1a2777e97

**Comment by MuesliSwapTeam** [comment]
Hi, thanks so much for the pull request!
However, could you change the file names to follow the format policy_id.name?
Also, the structure of the json file doesn't quite follow the requirements in the README.
Best regards,
Your MuesliSwap Team

**Comment by mr-eeee** [comment]
Sorry about that, the corrections have been made, thank you

**Comment by mr-eeee** [comment]
made a last minute change to the logo, but all corrections should be good now thanks

**Pull request merged**
