### PR TITLE
Listing request for PERNIS Token!

### PR DESCRIPTION
**Pull request by cedcardano**

### CODE REVIEW

**Comment by cedcardano** [comment]
Heya! Attached the files you should need to list PERNIS token - please let me know if anything is missing.

I have sent 50 ADA to the payment address (will attach tx id below) - but please consider waiving our fee! We're a mission driven project with a goal of supporting bird conservation and recently made our first donation of over 1000 ADA to Wild at Heart Arizona!

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
You should now be verified on MuesliSwap

**Comment by cedcardano** [comment]
Heya! Just wanted to check in - we've been unverified for some reason!

image

Any idea what's up? Thanks :)

**Comment by MuesliSwapTeam** [comment]
> Heya! Just wanted to check in - we've been unverified for some reason!
> 
> image
> 
> Any idea what's up? Thanks :)

Thanks for reaching out so quickly! Just re-added the verification status.

**Comment by MuesliSwapTeam** [comment]
Also updated the amounts so people can trade even larger quantities :+1:

**Pull request merged**
