### PR TITLE
Token Listing Blue Planet Token BLUP

### PR DESCRIPTION
**Pull request by kvolic**

### CODE REVIEW

**Comment by kvolic** [comment]
Fee TransactionID: e5ef1395dae744e18e640c7d5ab272b9b493cb3d193b42b5b06cf76629f2d4e4

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for opening the pull request.
One change request: Could you also include the policy id on your website or point us to where it is located?
Best regards,
Your MuesliSwap Team

**Comment by kvolic** [comment]
https://blueplanet-blup.com/impressum/

MuesliSwap Team ***@***.***> schrieb am Mi., 2. Feb. 2022,
00:28:

**Comment by kvolic** [comment]
Any further actions required from my side?

MuesliSwap Team ***@***.***> schrieb am Fr., 4. Feb. 2022,
13:42:

**Pull request merged**
