### PR TITLE
TICKET Token

### PR DESCRIPTION
**Pull request by curtindoavida**

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Thanks for the pull request!
Do you have a social media platform such as a Twitter page?
Besides that, we require a  verification fee of 50 ADA.

**Comment by curtindoavida** [comment]
the Twitter Page: https://twitter.com/rafflesocial1

how do we pay this verification fee

**Comment by curtindoavida** [comment]
Done 

https://cardanoscan.io/transaction/47375af8bdc8606accb8b8f9e009cb8b7270b1a5c2858b93f7fe748a1961411b?tab=utxo

**Comment by MuesliSwapTeam** [comment]
Thank you very much for the update!
You will soon be verified!

**Pull request merged**
