### PR TITLE
Added updated logo for CCCC

### PR DESCRIPTION
**Pull request by an0ndroid**
Added updated logo for CCCC

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for opening a pull request!

There is still some information missing, like the JSON file and the transaction id. 
Please check out the [README](https://github.com/MuesliSwapTeam/muesliswap-token-verification/blob/main/README.md) for a detailed description of the requirements.  
In case you have any questions, feel free to contact us. 

Best regards,
Your MuesliSwap Team

**Comment by MuesliSwapTeam** [comment]
Hi, thank you very much for updating.  
However, there are still a few changes to be made:  
1. There is a space in the filename of the image, that needs to be removed 
2. Please remove the JSON file which is not in the correct directory  
3. Please update the token name

**Comment by an0ndroid** [comment]
I updated png filename, json filename and coin name in json file to all match.

**Comment by MuesliSwapTeam** [comment]
Thank you for the update! 
The token was minted with the name "CCCC" so the "name" field in the JSON file also needs to be "CCCC" and the name of the files needs to be "policy_id"."name".
You could however change the symbol to "Cardano Community Charity Coin". 
Sorry if that was unclear!

**Comment by an0ndroid** [comment]
changed name to CCCC

**Comment by an0ndroid** [comment]
updated name of png

**Pull request merged**
