### PR TITLE
GADA-Finance-token-verification

### PR DESCRIPTION
**Pull request by Kulaneian**
payment id: https://cardanoscan.io/transaction/3cc37c67e1f37c5c34b293cfc1fc892722c02ab9a9a14a9ad61884496d271324

### CODE REVIEW

**Comment by Kulaneian** [comment]
payment id: https://cardanoscan.io/transaction/3cc37c67e1f37c5c34b293cfc1fc892722c02ab9a9a14a9ad61884496d271324

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!  
Looks good, but we were unable to find the policy-id on your website.  
Could you point us to it in case we missed it?

**Comment by Kulaneian** [comment]
Hi there,
So I have added the policy id to the tokenomics image on the landing page. 
You just have to go to gada.finance and then scroll down to the tokenomics image. 
It wasnt there before, but I have added it after I saw your comment.

**Comment by MuesliSwapTeam** [comment]
Great, thank you for the update!

**Pull request merged**
