### PR TITLE
Create 7d757d36ce79e19f224fd956aafe078d40f0999f944f36e42491def2

### PR DESCRIPTION
**Pull request by alloss**
Metadata for $SAFARI token
$safari token

### CODE REVIEW

**Comment by alloss** [comment]
https://safarisquad.io/ = website
https://medium.com/@safarisquad/afari-tokenomics-7cadb225697c = tokenomics
https://twitter.com/safarisquadnft

TX ID for 50 ADA payment:
b8172066b7c4da6c072fd8fafcb1dd670bcb965181bbdffe80c46ef336b34586

**Comment by MuesliSwapTeam** [comment]
Thank you very much for the pull request!
Could you please add the policyID to the website?
Besides that, everything looks good!

**Comment by alloss** [comment]
> 
I made some changes I think this should be correct now. Thank you! Do let me know if I need to change something else

**Comment by MuesliSwapTeam** [comment]
Thank you very much for the update!
You will be verified soon!

**Pull request merged**
