### PR TITLE
Add Hay Token

### PR DESCRIPTION
**Pull request by C-Fiekert**
TX ID: a0a133f0e481a7394d4cc6b6c9fd5289b08ee2b618def33b0e535e50bdbe7d87

Policy ID can be found at https://www.filthyrichhorses.com/faq on our website

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the pull request!
Do you have your tokenomics somewhere on your website and could point us to it?
Best regards!

**Comment by C-Fiekert** [comment]
Hi, thanks for getting back!
Our tokenomics can be viewed here on our website: https://www.filthyrichhorses.com/utility

**Comment by MuesliSwapTeam** [comment]
Sorry for the late reply and thank you for providing the link!
As tokenomics we require an overview of the tokens distribution (presale, team, rewards, etc. ). 
Sry if we missed it but is there such an overview?
Besides that everything looks good!
Best regards!

**Comment by C-Fiekert** [comment]
image
Hi and sorry for the confusion, here is an infographic containing our tokenomics :) @MuesliSwapTeam

**Comment by MuesliSwapTeam** [comment]
Perfect, thank you!

**Pull request merged**
