### PR TITLE
CardanoDOGE

### PR DESCRIPTION
**Pull request by RnA195**
transaction verification fee tx ID:
347941c5dbc5532859f05a83e871d875ddf12b3bd2408514ce0f894974d7b641

(forgot to put a message in the transaction - sorry)

email:
cradano.doge@gmail.com

This is the DOGE version in cardano eco-system.
We will like to coroporate with muesli DEX and in our roadmap we have a lot of offers to give to muesli users in order to increase the number of users in this DEX and also give you the win win situation.

We only at the beginning and we know we don't have everything yet but we working on it - so please give us the opportunity to make it and we will all win together.

Thank you.

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
However, the website seems to be broken. 
Could you fix it or provide a new link?

**Comment by RnA195** [comment]
> 

Hi,
The website got fixed. Sorry for the inconveniente.
Thank you very much!

**Comment by MuesliSwapTeam** [comment]
Thank you for the update!  
However, the website seems to be unreachable.   
Is the address in the JSON file correct?

**Comment by RnA195** [comment]
> Thank you for the update! However, the website seems to be unreachable. Is the address in the JSON file correct?

Thank you again - the address in the JSON is incorrect sorry..... the correct address is https://cdoge.info/

thank you.

**Comment by MuesliSwapTeam** [comment]
Thank you for the update, the website looks good!
However, the website is also missing some information, such as a token description, tokenomics contact information, and your policy id. 
Please refer to our description of which information is required.

**Comment by RnA195** [comment]
> Thank you for the update, the website looks good! However, the website is also missing some information, such as a token description, tokenomics contact information, and your policy id. Please refer to our description of which information is required.

Hi Muesli Team!
We are really sorry for all the inconvenience and we try to improve and add everything like your request and we really appreciate your comments and your help!
We already added the necessary information to the website- we hope it's will be better and approved now.

This token is a first token that minted with a very small total supply- we are working now on a bigger project with a new token and we will be really happy to get an email address from you to contact you in person and write you about our new roadmap and future plans.

Thank again- hope to contact you soon.

**Comment by MuesliSwapTeam** [comment]
Hi, sorry that the whole process is taking so long!
Also thank you for updating the address.  
However, it seems like the website still does not show information about tokenomics or a token description. 
You can also always contact us at contact@muesliswap.com

**Comment by RnA195** [comment]
> Hi, sorry that the whole process is taking so long! Also thank you for updating the address. However, it seems like the website still does not show information about tokenomics or a token description. You can also always contact us at [contact@muesliswap.com](mailto:contact@muesliswap.com)

Hi!it's ok we are happy to imporve ourself!
We updated the website with some descriptions and little bit of our future plans.
Hope it's will be ok.
We also write an email for you.
Thanks you again!

**Comment by MuesliSwapTeam** [comment]
Thanks for updating again! 
The only thing left on the website is an overview, of how you distribute the token (team, airdrop, etc.). 
Best regards!

**Comment by RnA195** [comment]
> Thanks for updating again! The only thing left on the website is an overview, of how you distribute the token (team, airdrop, etc.). Best regards!

Hi!
Thanks you again!
All updated and added as you requested.
Thank you very much!

**Pull request merged**
