### PR TITLE
Adding Adosia to the verification que.

### PR DESCRIPTION
**Pull request by Liberty-Chris**

### CODE REVIEW

**Comment by Liberty-Chris** [comment]
Transaction ID for 50A payment

6912fb668ae7607687d311442e08e7fc758d40e5c64ce2aea047b4ca89ea4e7b

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request! 
We could not find a token description and tokenomics on your website. 
In case we missed it, could you send a link?

**Comment by Liberty-Chris** [comment]
> Thanks a lot for the pull request! We could not find a token description and tokenomics on your website. In case we missed it, could you send a link?

Sure thing. Here you are:

https://logicalmechanism.gitbook.io/adosia-white-paper/supporting-information/tokenomics

**Comment by MuesliSwapTeam** [comment]
Thanks a lot! You have just been verified!

**Pull request merged**
