### PR TITLE
MUSIC verification

### PR DESCRIPTION
**Pull request by shehan11**
transaction: [transaction id 9d9647c9481fc77a55f18044bd2bb2773c822d3809e5d08749cf10c1952e8766](https://cardanoscan.io/transaction/9d9647c9481fc77a55f18044bd2bb2773c822d3809e5d08749cf10c1952e8766)

description: MUSIC Tokens are loyalty tokens that can be used on our platform

contact info: toby@livemusic.show

website: livemusic.show

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the pull request!
Do you also have an overview of your tokenomics and policy id listed on your website?

**Comment by MuesliSwapTeam** [comment]
Thanks for the update! 
It seems like your token is not yet registered via the official Cardano token registry (https://github.com/cardano-foundation/cardano-token-registry). Could you please do that in advance?
Besides that, do you happen to have a social media channel like Twitter or Discord?

**Comment by shehan11** [comment]
Thanks for your response. I'm having trouble setting up the JSON file to submit to the cardano token registry.

After installing nix, I have tried to install offchain-metadata-tools but there are always installation errors.

I have tried on Mac, Ubuntu, Kali, and Fedora all with issues. And it takes a long time to install that software. I wanted to see if maybe I'm going about it the wrong way and there was a simpler way to set up the JSON file. Thank you.

**Comment by MuesliSwapTeam** [comment]
Sorry to hear that you are experiencing difficulties!
All of the required steps are explained in detail in the following tutorial: https://developers.cardano.org/docs/native-tokens/cardano-token-registry/
If that doesn't work, could you show the error message you are receiving?

**Comment by shehan11** [comment]
I have registered with cardano:
https://github.com/shehan11/cardano-token-registry/commit/0490aaaa575806cabc4c72b84c3007dc8b7084df

**Pull request merged**
