### PR TITLE
verify slottery

### PR DESCRIPTION
**Pull request by slotterydev**
txid https://cardanoscan.io/transaction/1148709c384f4ffaa29593e41ff22da3c5ef079eaa6dc3c02698fde530a7bbf4

Tokenomics:
* Fixed supply
* No burns
* The policy is locked since the mint
* ~40% will be sold to the community using MuesliSwap
* 77,777 (1%) Tokens will be airdropped to Cardano community in a ratio through Dripdropz
* 10% team 
* The rest will be used for liquidity

https://cardanoassets.com/asset1mx00zs3rxffeqmsvt3e49jwsm79kjl6kpmeqm3

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
Could you also add the token image?

**Comment by slotterydev** [comment]
@MuesliSwapTeam done

**Comment by MuesliSwapTeam** [comment]
Thanks! Do you have social media presence like Twitter or Discord? 
We could not find it on your website.

**Comment by slotterydev** [comment]
Twitter for now, will have Discord soon
https://twitter.com/SlotteryFinance

**Pull request merged**
