### PR TITLE
Add Dance Token Request Listing

### PR DESCRIPTION
**Pull request by santoraphael**
See 0fdaa1b8699080ed281faec8dfae54531d07f37fe9a4bdd8f0733e2e.DANCE.json

Transaction
https://cardanoscan.io/transaction/4246fed02a68898afa5efa810343343dac65827bb70c9b4a6208beee6ebe2d16

### CODE REVIEW

**Comment by santoraphael** [comment]
Hello, how are you?
What is the deadline for validating the Token and it being listed, thanks!

**Comment by MuesliSwapTeam** [comment]
Hi, thank you for the request, and sorry that the process is taking so long!
However, it seems like the website does not show the policy id. 
You can get verified as soon as this information is available on the website.

**Comment by santoraphael** [comment]
Hi, how are you? @MuesliSwapTeam @
That's right, we had forgotten to add the policy id on the site, and we just did that.



[](http://cardance.finance/)

**Comment by santoraphael** [comment]
http://cardance.finance/

**Comment by MuesliSwapTeam** [comment]
Great, you should now be verified!

**Pull request merged**
