### PR TITLE
Verify Cavalier King Charles token

### PR DESCRIPTION
**Pull request by CharlyToken**
…y.json

### CODE REVIEW

**Comment by CharlyToken** [comment]
Tell me when I need to pay !!

Go Charly 

Featured soon ?

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
You can get verified as soon as you submit the verification fee.
Best regards!

**Comment by CharlyToken** [comment]
We already pay transaction id down below

d5dea82940048ad0248c7f23aa01a6002abdc8a37108a95cd618ec032f9d8019 time 3rd Apr 2022, 17:11:41 

Can you also do featured option, we already send you email for modificate our token, so all can buy bigger amounts.

Sincerely

Team Charly token

**Comment by CharlyToken** [comment]
> Hi, thanks for the pull request! You can get verified as soon as you submit the verification fee. Best regards!

Payed.

**Comment by CharlyToken** [comment]
Thanks Guys

**Pull request merged**
