### PR TITLE
False Idols Token (IDOL)

### PR DESCRIPTION
**Pull request by spward**
Transaction hash: 8764383550666dac1bf4a253ee8360363a6bf93f8bc03c5e8f2ef319ccb6da28

[Cardano Scan transaction](https://cardanoscan.io/transaction/8764383550666dac1bf4a253ee8360363a6bf93f8bc03c5e8f2ef319ccb6da28)

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
Could you please add your policy-id and your tokenomics (distribution of the token) to your whitepaper?
Besides that, there seems to be another version of your token:
https://muesliswap.com/swap?base=.&quote=552808f5ca140873e9d5bf52fbdcb215e5cbea836fdb4b06c23c9174.49444f4c
Is this an outdated version you created previously?

**Comment by spward** [comment]
https://whitepaper.falseidols.xyz/whitepaper/internal-ecosystem/usdidol

update to our whitepaper

**Comment by MuesliSwapTeam** [comment]
Thank you for the update! Could you please also add the tokenomics to the whitepaper?
It doesn't have to be a lot of text, but just a short summary or chart of how the token will be distributed (e.g. public sale, staking, team, etc.).

**Comment by MuesliSwapTeam** [comment]
Thanks for the update!
Could you share the link to the tokenomics, I can not find it in the whitepaper.
Or is it 100% that are distributed via staking?

**Comment by spward** [comment]
> 

Yes, it is 100% distributed through staking.
Our team does have NFTs that we're staking ourselves to do giveaways but the coin will be earned through staking.

**Comment by MuesliSwapTeam** [comment]
Thanks a lot! You have been verified!

**Pull request merged**
