### PR TITLE
Create TrustCoin

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
Final commit of TrustCoin. To get listed

https://twitter.com/GabrielMazzant3

### CODE REVIEW

**Comment by GabrielMazzanti** [comment]
can I pay ?

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request, but do you also have a website with tokenomics, token description, and the policy id?
Best regards!

**Comment by GabrielMazzanti** [comment]
Hey, Yes, https://site-6868308-689-3621.mystrikingly.com/
It is on my Twitter Account The tokenomics are to burn unsold in about 3 - 4 months for all of my tokens maybe 20% is already in circulation by giveaways... so about 60% will get burnt

**Comment by GabrielMazzanti** [comment]
Everything is on my twitter I used my name on this...

**Comment by GabrielMazzanti** [comment]
this is almost an exclusive twitter, discord campain...

**Comment by MuesliSwapTeam** [comment]
Thanks for providing the information! Could you your tokenomics somewhere on your website? Besides that everything looks fine!

**Comment by GabrielMazzanti** [comment]
Okay it is done, I explained that in Q2 2022 all unsold or ungiven will be
burnt!!!

Thanks

Le sam. 12 févr. 2022 à 00:44, MuesliSwap Team ***@***.***> a
écrit :

**Comment by MuesliSwapTeam** [comment]
Thank you, we can verify your token if you send the fee of 50 ADA.

**Comment by GabrielMazzanti** [comment]
done, i'll comment transaction hash

**Comment by GabrielMazzanti** [comment]
Okay !!!!!!
https://cardanoscan.io/transaction/f270a54e6f1229251af325e7e9bc28c5e2b59c28da4d9fb4f7c42df888041c71

**Pull request merged**
