### PR TITLE
Add Buffer (BUFS) token - 50 ADA submitted

### PR DESCRIPTION
**Pull request by BierblikRick**

### CODE REVIEW

**Comment by BierblikRick** [comment]
Transactie ID
a08657e688a8490208705ed6948f67930ea31887e61ce5876eae4c7595ff5ba9

**Comment by MuesliSwapTeam** [comment]
Hi, thanks for the pull request!
Could you please also publish a token description, tokenomics, and policy-ID on your website?
In case we missed it, could you point us to it?

**Comment by BierblikRick** [comment]
I've edited it, it's now visible on the site

**Comment by MuesliSwapTeam** [comment]
Thank you for the update!
You have been verified!

**Comment by BierblikRick** [comment]
My icon is not visible on the site.

**Pull request merged**
