### PR TITLE
MNT Token verification. 

### PR DESCRIPTION
**Pull request by marcosncosta1**
My token is already listed on Muesliswap but it is not verified. I had never send the 50ADA. Here it is.
Thanks

muesli_verification

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
Hi, thanks a lot for the pull request and sending the verification fee!
Could you make the whitepaper public, so the community does not need to request access in order to view it?
Alternatively, could you publish your tokenomics on your website?

**Comment by marcosncosta1** [comment]
Hi, thanks for the feedback. 
I added the whitepaper as part of the page so that users can see it right away and left the option to download it below. 
Also I included a section to the page with the tokenomics as well. This is also included in the whitepaper file available for download. 
Please let me know if any other changes are needed.

**Comment by MuesliSwapTeam** [comment]
Thanks a lot for the update! You have just been verified!

**Comment by marcosncosta1** [comment]
Thanks for the merge. Quick question. I just noticed there's another token with the same Ticker "MNT". Would that be a conflict? What are the options for me to change the ticker? I guess I would have to change both at he Cardano registry and with your guys correct?

**Pull request merged**
